window.ZUB_APPS=[
{name:'Netflix',keys:['netflix'],regions:[['US','Лучший выбор для US-каталога'],['GB','UK-каталог'],['JP','Японский каталог'],['CA','Канада']]},
{name:'Hulu',keys:['hulu'],regions:[['US','Основной регион сервиса']]},
{name:'BBC iPlayer',keys:['bbc','iplayer'],regions:[['GB','Основной регион сервиса']]},
{name:'ITVX',keys:['itvx'],regions:[['GB','Основной регион сервиса']]},
{name:'Peacock',keys:['peacock'],regions:[['US','Основной регион сервиса']]},
{name:'Paramount+',keys:['paramount'],regions:[['US','US-каталог'],['GB','UK-каталог'],['CA','Канада']]},
{name:'Max / HBO',keys:['max','hbo'],regions:[['US','US-каталог'],['NL','Быстрый EU-маршрут']]},
{name:'Disney+',keys:['disney'],regions:[['US','US-каталог'],['GB','UK'],['DE','Быстрый EU'],['JP','Japan']]},
{name:'Prime Video',keys:['prime','amazon video'],regions:[['US','US-каталог'],['GB','UK'],['DE','EU'],['JP','Japan']]},
{name:'YouTube',keys:['youtube'],regions:[['DE','Быстрый EU'],['NL','Стабильный EU'],['US','US-регион']]},
{name:'YouTube TV',keys:['youtube tv'],regions:[['US','Основной регион сервиса']]},
{name:'Tubi',keys:['tubi'],regions:[['US','Основной каталог']]},
{name:'Pluto TV',keys:['pluto'],regions:[['US','US-каталог'],['GB','UK'],['DE','Germany']]},
{name:'ESPN',keys:['espn'],regions:[['US','US sports']]},
{name:'Sling TV',keys:['sling'],regions:[['US','US live TV']]},
{name:'Fubo',keys:['fubo'],regions:[['US','US sports'],['CA','Canada']]},
{name:'DAZN',keys:['dazn'],regions:[['GB','UK'],['DE','Germany'],['JP','Japan'],['CA','Canada']]},
{name:'TikTok',keys:['tiktok','тик ток'],regions:[['DE','Низкая задержка EU'],['NL','Стабильный EU'],['US','US-регион'],['JP','Japan']]},
{name:'Instagram',keys:['instagram','инстаграм'],regions:[['DE','Низкая задержка EU'],['NL','Стабильный EU'],['FI','Nordic fallback']]},
{name:'Facebook',keys:['facebook'],regions:[['DE','Низкая задержка EU'],['NL','Стабильный EU']]},
{name:'X / Twitter',keys:['twitter','x.com','твиттер'],regions:[['DE','Низкая задержка EU'],['NL','Стабильный EU']]},
{name:'Reddit',keys:['reddit'],regions:[['DE','Быстрый EU'],['NL','Быстрый EU'],['US','US']]},
{name:'Discord',keys:['discord'],regions:[['DE','Низкий ping EU'],['NL','Стабильный EU'],['FI','Nordic']]},
{name:'Telegram',keys:['telegram','телеграм'],regions:[['DE','Низкий ping EU'],['NL','Стабильный EU'],['FI','Nordic']]},
{name:'WhatsApp',keys:['whatsapp','ватсап'],regions:[['DE','Низкий ping EU'],['NL','Стабильный EU']]},
{name:'Spotify',keys:['spotify'],regions:[['DE','Быстрый EU'],['NL','Быстрый EU'],['US','US-регион']]},
{name:'Apple Music',keys:['apple music'],regions:[['DE','Быстрый EU'],['NL','EU'],['US','US']]},
{name:'Twitch',keys:['twitch'],regions:[['DE','Низкий ping EU'],['NL','Стабильный EU'],['US','US']]},
{name:'ChatGPT',keys:['chatgpt','openai','чатгпт'],regions:[['DE','Быстрый EU'],['NL','Стабильный EU'],['US','US']]},
{name:'Claude',keys:['claude','anthropic'],regions:[['DE','Быстрый EU'],['NL','EU'],['US','US']]},
{name:'Gemini',keys:['gemini'],regions:[['DE','Быстрый EU'],['NL','EU'],['US','US']]},
{name:'PlayStation Network',keys:['playstation','psn'],regions:[['DE','Низкий ping EU'],['NL','EU'],['GB','UK']]},
{name:'Xbox',keys:['xbox'],regions:[['DE','Низкий ping EU'],['NL','EU'],['GB','UK']]},
{name:'Steam',keys:['steam'],regions:[['DE','Низкий ping EU'],['NL','EU'],['FI','Nordic']]},
{name:'GeForce NOW',keys:['geforce','nvidia'],regions:[['DE','Gaming EU'],['NL','Gaming EU'],['GB','UK']]},
{name:'Roblox',keys:['roblox'],regions:[['DE','Низкий ping EU'],['NL','EU'],['US','US']]},
{name:'Fortnite',keys:['fortnite','epic'],regions:[['DE','Низкий ping EU'],['NL','EU'],['GB','UK']]},
{name:'Valorant',keys:['valorant'],regions:[['DE','Низкий ping EU'],['NL','EU'],['PL','Central EU']]},
{name:'CS2',keys:['cs2','counter strike'],regions:[['DE','Низкий ping EU'],['NL','EU'],['FI','Nordic']]},
{name:'PUBG',keys:['pubg'],regions:[['DE','EU'],['SG','Asia'],['KR','Korea']]},
{name:'Mobile Legends',keys:['mobile legends','mlbb'],regions:[['SG','Asia hub'],['JP','Japan'],['KR','Korea']]},
{name:'TVING',keys:['tving'],regions:[['KR','Korean service']]},
{name:'Wavve',keys:['wavve'],regions:[['KR','Korean service']]},
{name:'Abema',keys:['abema'],regions:[['JP','Japanese service']]},
{name:'TVer',keys:['tver'],regions:[['JP','Japanese service']]},
{name:'Hotstar',keys:['hotstar','jiocinema'],regions:[['IN','India'],['SG','Asia fallback']]},
{name:'Kayo Sports',keys:['kayo'],regions:[['AU','Australia']]},
{name:'Stan',keys:['stan'],regions:[['AU','Australia']]},
{name:'Viaplay',keys:['viaplay'],regions:[['SE','Nordic'],['NO','Nordic'],['DK','Nordic'],['FI','Nordic']]},
{name:'Canal+',keys:['canal+','canal plus'],regions:[['FR','France']]},
{name:'Molotov',keys:['molotov'],regions:[['FR','France']]},
{name:'RTL+',keys:['rtl+','rtl plus'],regions:[['DE','Germany']]},
{name:'Joyn',keys:['joyn'],regions:[['DE','Germany']]},
{name:'Zattoo',keys:['zattoo'],regions:[['CH','Switzerland'],['DE','Germany']]},
{name:'RaiPlay',keys:['raiplay'],regions:[['IT','Italy']]},
{name:'Mediaset Infinity',keys:['mediaset'],regions:[['IT','Italy']]},
{name:'Atresplayer',keys:['atresplayer'],regions:[['ES','Spain']]},
{name:'RTVE Play',keys:['rtve'],regions:[['ES','Spain']]}
];