'use strict';
const {REGIONS,TIERS,tier,generate,valid,key}=PlateEngine;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], tg=window.Telegram?.WebApp;
const storageKey='nomer-v1-'+(tg?.initDataUnsafe?.user?.id||'local');
let state={rolls:0,collection:[],history:[],current:null,region:'all',fast:false,sound:false,haptic:true,best:-1},busy=false,filter='all',page='hunt',detail=null,timer,audio;
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved&&typeof saved==='object'){state={...state,...saved};state.collection=(Array.isArray(saved.collection)?saved.collection:[]).filter(valid).slice(0,5000);state.history=(Array.isArray(saved.history)?saved.history:[]).filter(valid).slice(0,12);state.current=valid(saved.current)?saved.current:null;if(!REGIONS.some(r=>r.code===state.region))state.region='all';state.rolls=Math.max(0,Number(state.rolls)||0);state.best=Math.max(-1,Math.min(5,Number(state.best)||0));}}catch{showToast('Не удалось прочитать сохранение');}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state));return true}catch{showToast('Память заполнена. Экспортируй коллекцию.');return false}}
function showToast(text){clearTimeout(timer);$('#toast').textContent=text;$('#toast').classList.add('visible');timer=setTimeout(()=>$('#toast').classList.remove('visible'),2700)}
function regionName(code){return REGIONS.find(r=>r.code===code)?.name||'Все регионы'}
function plate(p){return `<div class="plate" aria-label="${key(p)}"><div class="plate-main"><span class="letter">${p.a}</span><span class="digits">${p.n}</span><span class="letter">${p.b}${p.c}</span></div><div class="plate-region"><strong>${p.r}</strong><div class="plate-country">RUS<i class="flag"></i></div></div></div>`}
function isSaved(p){return state.collection.some(x=>key(x)===key(p))}
function display(p,preview=false){$('#plateWrap').innerHTML=plate(p);if(preview)return;const t=TIERS[tier(p)];$('#stage').style.setProperty('--rarity',t.color);$('#rarity').textContent=t.name.toUpperCase();$('#stageLabel').textContent='НОМЕР ВЫДАН';$('#regionLabel').textContent=regionName(p.r);$('#result').innerHTML=`<h2 style="color:${t.color}">${t.name}</h2><p>${reason(p)}</p>`;$('#save').hidden=false;$('#save').disabled=isSaved(p);$('#save').textContent=isSaved(p)?'✓ Уже в коллекции':'＋ В коллекцию';}
function reason(p){return ['У каждого номера начинается своя история','Красота в повторении','Сочетание, которое хочется оставить','Особенная серия. Забирай в коллекцию.','Три цифры. Один идеальный ритм.','Три буквы. Три цифры. Полное совпадение.'][tier(p)]}
function renderStats(){$('#rolls').textContent=state.rolls.toLocaleString('ru');$('#serial').textContent=String(state.rolls).padStart(4,'0');$('#owned').textContent=state.collection.length;$('#best').textContent=state.best>=0?TIERS[state.best].name:'—';$('#collectionCount').textContent=state.collection.length;$('#chosenRegion').textContent=state.region==='all'?'Все регионы':state.region+' · '+regionName(state.region);$('#fast').setAttribute('aria-pressed',Boolean(state.fast));}
function renderHistory(){$('#history').innerHTML=state.history.length?state.history.slice(0,6).map(p=>`<button class="history-row" data-id="${p.id}" style="--rarity:${TIERS[tier(p)].color}"><div class="mini">${plate(p)}</div><div class="history-meta"><b>${TIERS[tier(p)].name}</b><p>${regionName(p.r)}</p></div><span class="history-save">${isSaved(p)?'✓':'＋'}</span></button>`).join(''):'<div class="empty-inline">Здесь появятся твои находки</div>';}
function navigate(next){page=next;$$('.page').forEach(x=>x.hidden=x.id!==next);$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===next));if(next==='collection')renderCollection();try{if(next==='hunt')tg?.BackButton.hide();else tg?.BackButton.show();}catch{}window.scrollTo({top:0,behavior:'instant'});}
function renderCollection(){renderStats();let list=state.collection.filter(p=>(filter!=='favorite'||p.favorite)&&(filter!=='rare'||tier(p)>=2));const query=$('#search').value.toLowerCase().replace(/\s/g,'');if(query)list=list.filter(p=>(key(p)+regionName(p.r)).toLowerCase().replace(/\s/g,'').includes(query));list.sort($('#sort').value==='rare'?(a,b)=>tier(b)-tier(a)||b.at-a.at:(a,b)=>b.at-a.at);$('#collectionList').innerHTML=list.length?list.map(p=>`<button class="collect-card" data-id="${p.id}" style="--rarity:${TIERS[tier(p)].color}">${plate(p)}<div class="card-footer"><span>${TIERS[tier(p)].name}</span><span>${p.favorite?'★':'◇'}</span></div></button>`).join(''):`<div class="empty"><span>▦</span><h2>${state.collection.length?'Ничего не нашлось':'Здесь будут твои трофеи'}</h2><p>${state.collection.length?'Попробуй другой запрос или фильтр.':'Выбивай номера и сохраняй понравившиеся.<br>Начни с первого счастливого сочетания.'}</p><button class="primary" id="emptyRoll">Выбить номер</button></div>`;$('#emptyRoll')?.addEventListener('click',()=>navigate('hunt'));}
function savePlate(p){if(isSaved(p)){showToast('Этот номер уже в коллекции');return;}if(state.collection.length>=5000){showToast('Лимит 5 000 номеров. Экспортируй коллекцию.');return;}state.collection.push({...p});persist();renderStats();renderHistory();if(state.current)display(state.current);showToast('Номер добавлен в коллекцию');}
function tick(end=false){if(state.haptic){try{end?tg?.HapticFeedback.notificationOccurred('success'):tg?.HapticFeedback.selectionChanged()}catch{}}if(!state.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.setValueAtTime(end?880:280,audio.currentTime);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.start();o.stop(audio.currentTime+.09)}catch{}}
async function roll(){if(busy)return;busy=true;$('#roll').disabled=true;$('#save').hidden=true;$('#stage').classList.remove('reveal');$('#stage').classList.add('rolling');$('#stageLabel').textContent='ПОДБИРАЕМ КОМБИНАЦИЮ';$('#rarity').textContent='ВЫДАЧА';$('#result').innerHTML='<h2>Ловим твоё сочетание…</h2><p>Следующий номер может стать особенным</p>';const final=generate(state.region), reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const steps=reduced?1:state.fast?5:16;for(let i=0;i<steps;i++){display(generate(state.region),true);tick();await new Promise(r=>setTimeout(r,reduced?0:state.fast?45:40+i*6));}state.current=final;state.rolls++;state.best=Math.max(state.best,tier(final));state.history=[final,...state.history].slice(0,12);persist();display(final);renderStats();renderHistory();$('#stage').classList.remove('rolling');$('#stage').classList.add('reveal');$('#roll').disabled=false;$('#roll>span').textContent='ВЫБИТЬ ЕЩЁ';busy=false;tick(true);}
function showDetail(p){detail=p;const t=TIERS[tier(p)],saved=state.collection.find(x=>key(x)===key(p));$('#detailContent').style.setProperty('--rarity',t.color);$('#detailContent').innerHTML=plate(p)+`<h3>${t.name}</h3><p>${regionName(p.r)} · ${new Date(p.at).toLocaleDateString('ru')}</p><p>${t.desc}</p>${saved?`<button class="secondary" id="favorite">${saved.favorite?'★ Убрать из избранного':'☆ В избранное'}</button>`:'<button class="primary" id="detailSave">В коллекцию</button>'}<button class="secondary" id="copyPlate">Скопировать номер</button>${saved?'<button class="secondary" id="removePlate">Убрать из коллекции</button>':''}`;$('#detailSave')?.addEventListener('click',()=>{savePlate(p);showDetail(p)});$('#favorite')?.addEventListener('click',()=>{saved.favorite=!saved.favorite;persist();renderCollection();showDetail(p)});$('#copyPlate').onclick=async()=>{try{await navigator.clipboard.writeText(key(p));showToast('Номер скопирован')}catch{showToast(key(p))}};$('#removePlate')?.addEventListener('click',()=>{state.collection=state.collection.filter(x=>key(x)!==key(p));persist();$('#detailDialog').close();renderCollection();renderHistory();if(state.current)display(state.current);showToast('Убрано из коллекции')});if(!$('#detailDialog').open)$('#detailDialog').showModal();}
function renderRegions(){const query=$('#regionSearch').value.toLowerCase().trim();$('#regionList').innerHTML=(!query?`<button class="region-option ${state.region==='all'?'selected':''}" data-region="all"><span>◎</span>Все регионы</button>`:'')+REGIONS.filter(r=>(r.code+' '+r.name).toLowerCase().includes(query)).map(r=>`<button class="region-option ${state.region===r.code?'selected':''}" data-region="${r.code}"><span>${r.code}</span>${r.name}</button>`).join('');if(!$('#regionList').children.length)$('#regionList').innerHTML='<p class="muted">Регион не найден</p>';}
$('#roll').onclick=roll;$('#save').onclick=()=>state.current&&savePlate(state.current);$('#fast').onclick=()=>{state.fast=!state.fast;persist();renderStats()};$('#regionButton').onclick=()=>{$('#regionSearch').value='';renderRegions();$('#regionDialog').showModal()};$('#regionSearch').oninput=renderRegions;$('#regionList').onclick=e=>{const b=e.target.closest('[data-region]');if(!b)return;state.region=b.dataset.region;persist();renderStats();$('#regionDialog').close()};$('#settings').onclick=()=>{$('#sound').checked=state.sound;$('#haptic').checked=state.haptic;$('#settingsDialog').showModal()};for(const name of ['sound','haptic'])$('#'+name).onchange=e=>{state[name]=e.target.checked;persist();if(name==='sound')tick(true)};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));$$('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('.brand').onclick=e=>{e.preventDefault();navigate('hunt')};$('#viewCollection').onclick=()=>navigate('collection');$('#search').oninput=renderCollection;$('#sort').onchange=renderCollection;$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCollection()});for(const sel of ['#history','#collectionList'])$(sel).onclick=e=>{const b=e.target.closest('[data-id]');if(b){const p=[...state.collection,...state.history].find(p=>p.id===b.dataset.id);if(p)showDetail(p)}};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,collection:state.collection},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nomer-collection.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Копия коллекции подготовлена')};$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error();const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.collection)||!data.collection.every(valid))throw Error();const merged=new Map(state.collection.map(p=>[key(p),p]));data.collection.forEach(p=>merged.set(key(p),{a:p.a,b:p.b,c:p.c,n:p.n,r:p.r,id:p.id,at:p.at,favorite:Boolean(p.favorite)}));if(merged.size>5000)throw Error();state.collection=[...merged.values()];persist();renderStats();renderHistory();showToast('Коллекция импортирована')}catch{showToast('Не удалось импортировать файл коллекции')}e.target.value='';};
$('#rarityGuide').innerHTML=[...TIERS].reverse().map((t,i)=>{const [a,n,b,c]=t.example;return `<div class="guide-row" style="--rarity:${t.color}"><div class="mini">${plate({a,n,b,c,r:'77'})}</div><div><h2>${t.name}</h2><p>${t.desc}</p></div></div>`}).join('');$('#poolSize').textContent=`В каталоге ${REGIONS.length} кодов, включая исторические. ${ (12**3*999).toLocaleString('ru')} сочетаний на каждый регион. Вероятность ультраредкого номера — 1 из 15 984.`;
renderStats();renderHistory();if(state.current)display(state.current);else $('#plateWrap').innerHTML=plate({a:'А',n:'777',b:'А',c:'А',r:'777'});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&page==='hunt'&&!$('dialog[open]')&&!['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();roll()}});try{tg?.ready();tg?.expand();tg?.setHeaderColor('#101214');tg?.setBackgroundColor('#101214');tg?.BackButton.onClick(()=>navigate('hunt'));}catch{}
