'use strict';
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const TOKEN=process.env.TELEGRAM_BOT_TOKEN;
const PORT=Number(process.env.PORT||10000);
const APP=process.env.MINI_APP_URL||'https://ride-hub-qr-test.onrender.com';
const TG=TOKEN?`https://api.telegram.org/bot${TOKEN}`:'';
const ROOT=path.resolve(__dirname,'../ride-hub');
const files={'/':['index.html','text/html; charset=utf-8'],'/index.html':['index.html','text/html; charset=utf-8'],'/plates.css':['plates.css','text/css; charset=utf-8'],'/plates.js':['plates.js','text/javascript; charset=utf-8'],'/plate-engine.js':['plate-engine.js','text/javascript; charset=utf-8']};
function esc(s){return String(s).replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]));}
async function api(method,body){if(!TOKEN)return null;try{const r=await fetch(`${TG}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!data.ok)console.error('Telegram method failed',method,data.error_code);return data}catch{console.error('Telegram connection failed',method);return null}}
function keyboard(){return{inline_keyboard:[[{text:'Выбить номер',web_app:{url:APP}}]]};}
async function handle(m){if(m.chat?.type!=='private')return;const command=(m.text||'').split('@')[0].split(' ')[0];if(!['/start','/app','/help'].includes(command))return;const name=esc(m.from?.first_name||'друг');const text=command==='/help'?'Выбивай виртуальные автомобильные номера и сохраняй лучшие сочетания.\n\nВсе попытки бесплатные. Коллекция хранится на твоём устройстве. В настройках есть экспорт и импорт.\n\nРедкость зависит от сочетания букв и цифр — правила внутри приложения.':`<b>НОМЕР · привет, ${name}!</b>\n\nТвой следующий трофей — одно нажатие.\nВыбивай номера, находи редкие сочетания и собирай собственную коллекцию.\n\n12 букв · 999 комбинаций цифр · выбор региона\n\n<b>Бесплатно и без ограничений.</b>`;await api('sendMessage',{chat_id:m.chat.id,text,parse_mode:'HTML',reply_markup:keyboard()});}
let offset=0,stopped=false;
async function poll(){while(!stopped){try{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),35000);let r;try{r=await fetch(`${TG}/getUpdates?timeout=25&offset=${offset}&allowed_updates=%5B%22message%22%5D`,{signal:controller.signal}).then(x=>x.json())}finally{clearTimeout(timeout)}if(!r.ok){console.error('Polling failed',r.error_code);await new Promise(r=>setTimeout(r,3000));continue}for(const u of r.result||[]){offset=u.update_id+1;if(u.message)await handle(u.message)}}catch{console.error('Polling connection failed');await new Promise(r=>setTimeout(r,3000))}}}
async function setup(){if(!TOKEN)return console.log('Preview mode: Telegram token not configured');await api('deleteWebhook',{drop_pending_updates:false});await api('setMyCommands',{commands:[{command:'start',description:'Выбить красивый номер'},{command:'app',description:'Открыть коллекцию номеров'},{command:'help',description:'Как играть'}]});await api('setMyDescription',{description:'НОМЕР — игра про красивые автомобильные номера. Выбивай сочетания, находи редкости и собирай коллекцию. Бесплатно, без ограничений.'});await api('setMyShortDescription',{short_description:'Красивые номера. Редкие сочетания. Твоя коллекция.'});await api('setChatMenuButton',{menu_button:{type:'web_app',text:'Выбить номер',web_app:{url:APP}}});poll();}
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,service:'nomer-bot',telegramConfigured:Boolean(TOKEN)}))}const file=files[url.pathname];if(!file){res.writeHead(404);return res.end('Not found')}try{const data=fs.readFileSync(path.join(ROOT,file[0]));res.writeHead(200,{'content-type':file[1],'cache-control':'no-cache','x-content-type-options':'nosniff'});res.end(req.method==='HEAD'?undefined:data)}catch{res.writeHead(500);res.end('Application files unavailable')}});
server.listen(PORT,'0.0.0.0',()=>{console.log('NOMER server ready');setup()});process.on('SIGTERM',()=>{stopped=true;server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),5000).unref()});
